### ISSUE TITLE
Implement entry method for mutable cursor

### ISSUE THREAD

**Issue by sergeyfedotov** [Amanieu/intrusive-rs#10]
Are there any drawbacks with implementing entry method for CursorMut? 

Like this: https://github.com/sergeyfedotov/intrusive-rs/blob/2b9d41c5b7fe87edbb1d91ad1eee6a32c0fa3d83/src/rbtree.rs#L795

**Comment by Amanieu** [comment]
This is actually unsound because `Entry` can return a `CursorMut`. This `CursorMut` could be used to unlink the element which the current `CursorMut` is pointing to.

**Comment by sergeyfedotov** [comment]
ok. It sounds reasonable.
