### ISSUE TITLE
Order considerations for rbtree::CursorMut::replace_with?

### ISSUE THREAD

**Issue by cmr** [Amanieu/intrusive-rs#2]
Does this function have any order considerations? That is, does the replaced object need to have the same sort order as the object being replaced? Either way, I think the answer should be in the rustdocs.

**Comment by Amanieu** [comment]
Thanks! I seem to have forgotten about this when writing the docs.

There are ordering considerations in that violating the order can make `find`, `upper_bound`, `lower_bound` and `range` return incorrect results, however this isn't unsafe because this does not impact memory safety.
