### ISSUE TITLE
intrusive_adapter! shoud implement Default and not derive it

### ISSUE THREAD

**Issue by agalakhov** [Amanieu/intrusive-rs#22]
Hi,

first, thank you for the great crate. I found a small issue: if I use `intrusive_adapter!` macro for a type that does not implement `Default`, it will fail. Actually it does not depend on this `Default` since it's `PhantomData`. This is a little bit confusing and requires writing of custom `Adapter` implementation which does exactly the same as the macro one. I believe an implementation should be used instead of `derive`. Maybe the same for `Clone` too, and may be it is even `Copy`.

**Comment by Amanieu** [comment]
Fixed in 0.7.6
