### ISSUE TITLE
Going from an Iter to an Rc or Arc strong reference

### ISSUE THREAD

**Issue by bonzini** [Amanieu/intrusive-rs#24]
When iterating over a list where the storage type is Rc<T> Arc<T>, it is only possible to get an `Option<&A::Value>`, which of course is subject to the borrow checker rules. It is not possible to get an item as a strong reference, i.e. as an Option<A::Pointer>.

In some cases, if the list nodes are reference counted, it would be handy to just get an extra reference to the value. I could not find any way to do this safely (I am currently retrieving the Arc via IntrusivePointer, which is unsafe, then cloning it and finally forgetting the temporary instance). Would it be hard to add this functionality?

**Comment by Amanieu** [comment]
We could add a `clone()` method to `Cursor` and `CursorMut` which would do what you are suggesting. The implementation would be almost identical to what you are doing right now.

Are you willing to make a PR for this feature?

**Comment by bonzini** [comment]
Heh, I thought what I did was a hack. If it's the right way to do it, I can give it a shot.

**Comment by Matthias247** [comment]
I would currently require the same. It seems like the `Cursor`s offer `.get()`, which returns  `&A::Value`, but I actually require `A::Pointer` (which is in my case a Rc<A::Value>).
