### ISSUE TITLE
splice with mutable reference

### ISSUE THREAD

**Issue by jynnantonix** [Amanieu/intrusive-rs#43]
It would be nice to have a way to splice a `LinkedList` into another `LinkedList` via mutable reference.  The use case is that I have 2 structs, each of which contain a `LinkedList`, and I would like to transfer all the elements from one `LinkedList` into the other.

Unfortunately, since both `splice_before` and `splice_after` take the other list by value and not by mutable reference, I have to work around it with `mem::replace`:

```rust
struct Foo {
    list: LinkedList<Adapter>,
    other_field: u64,
}

fn transfer(from: &mut Foo, to: &mut Foo) {
    to.list.cursor_mut().splice_before(mem::replace(
        &mut from.list,
        LinkedList::new(Adapter::new()),
    ));
}
```

This feels a bit hacky and it would be nice if `CursorMut` provided `splice_*` methods that took the other list by mutable reference.

**Comment by Amanieu** [comment]
You can use the `take` method on `LinkedList`:
```rust
fn transfer(from: &mut Foo, to: &mut Foo) {
    to.list.cursor_mut().splice_before(from.list.take());
}
```
